
# raw output of fields from submission

9:36:49 AM b59f6bcc INFO   {
  number: 7,
  title: null,
  email: 'jonjonmcjon@outlook.com',
  name: null,
  first_name: null,
  last_name: null,
  company: null,
  summary: 'jonjonmcjon@outlook.com',
  body: null,
  data: {
    email: 'jonjonmcjon@outlook.com',
    ip: '98.247.102.69',
    user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36',
    referrer: 'https://test.seattlecreative.directory/'
  },
  created_at: '2021-05-27T16:36:48.794Z',
  human_fields: { Email: 'jonjonmcjon@outlook.com' },
  ordered_human_fields: [
    { title: 'Email', name: 'email', value: 'jonjonmcjon@outlook.com' }
  ],
  id: '60afcaa041bf1500ba440822',
  form_id: '60a5d2e97ff83000087f255a',
  site_url: 'https://seattlecreative.directory',
  form_name: 'Subscribe - Buttondown'
}



9:36:49 AM b59f6bcc Duration: 5.70 ms	Memory Usage: 65 MB	Init Duration: 163.66 ms
9:37:32 AM 72863ab8 INFO   {
  number: 7,
  title: 'jonjonmcjon@outlook.com',
  email: 'jonjonmcjon@outlook.com',
  name: null,
  first_name: null,
  last_name: null,
  company: null,
  summary: '<strong>jonjonmcjon@outlook.com</strong> ',
  body: null,
  data: {
    submitContact: 'jonjonmcjon@outlook.com',
    submitName: 'business',
    submitWebsite: 'url',
    submitSocial: '@jonmccon',
    submitNeighborhood: 'maple valley',
    submitSize: '11-40',
    rendering: '',
    advertising: 'advertising',
    architecture: '',
    branding: '',
    community: '',
    development: '',
    environmental: '',
    events: '',
    exhibition: '',
    experiential: '',
    gaming: 'gaming',
    illustration: '',
    industrial: 'industrial',
    interior: '',
    marketing: '',
    motion: 'motion',
    naming: 'naming',
    packaging: '',
    photography: '',
    presentation: '',
    print: '',
    product: '',
    publicRelations: '',
    research: '',
    education: '',
    strategy: '',
    typography: '',
    uxui: '',
    vfx: '',
    video: '',
    sound: '',
    voice: '',
    virtualReality: '',
    eCommerce: '',
    submitGuest: '',
    submitPrint: 'yes for sure',
    submitNotes: 'make a map and shit and print it',
    ip: '98.247.102.69',
    user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36',
    referrer: 'https://test.seattlecreative.directory/submit'
  },
  created_at: '2021-05-27T16:37:31.724Z',
  human_fields: {
    'What is your email?': 'jonjonmcjon@outlook.com',
    'What is the name of your business?': 'business',
    'Business website or primary web address:': 'url',
    'Any social accounts or additional urls you want to include?': '@jonmccon',
    'What neighborhood is your primary location in?': 'maple valley',
    '1-4': '11-40',
    '3D rendering': '',
    advertising: 'advertising',
    architecture: '',
    branding: '',
    community: '',
    development: '',
    environmental: '',
    events: '',
    exhibition: '',
    experiential: '',
    gaming: 'gaming',
    illustration: '',
    industrial: 'industrial',
    interior: '',
    marketing: '',
    motion: 'motion',
    naming: 'naming',
    packaging: '',
    photography: '',
    presentation: '',
    print: '',
    product: '',
    'public relations': '',
    research: '',
    education: '',
    strategy: '',
    typography: '',
    'UX/UI': '',
    vfx: '',
    video: '',
    sound: '',
    voice: '',
    'virtual reality': '',
    eCommerce: '',
    'Would you like to be a guest on the show? Or do you want to hear from someone specifically?': '',
    'Would you buy a hardcopy printed directory?': 'yes for sure',
    'If you have any questions or suggestions, let us know:': 'make a map and shit and print it'
  },
  ordered_human_fields: [
    {
      title: 'What is your email?',
      name: 'submitContact',
      value: 'jonjonmcjon@outlook.com'
    },
    {
      title: 'What is the name of your business?',
      name: 'submitName',
      value: 'business'
    },
    {
      title: 'Business website or primary web address:',
      name: 'submitWebsite',
      value: 'url'
    },
    {
      title: 'Any social accounts or additional urls you want to include?',
      name: 'submitSocial',
      value: '@jonmccon'
    },
    {
      title: 'What neighborhood is your primary location in?',
      name: 'submitNeighborhood',
      value: 'maple valley'
    },
    { title: '1-4', name: 'submitSize', value: '11-40' },
    { title: '3D rendering', name: 'rendering', value: '' },
    { title: 'advertising', name: 'advertising', value: 'advertising' },
    { title: 'architecture', name: 'architecture', value: '' },
    { title: 'branding', name: 'branding', value: '' },
    { title: 'community', name: 'community', value: '' },
    { title: 'development', name: 'development', value: '' },
    { title: 'environmental', name: 'environmental', value: '' },
    { title: 'events', name: 'events', value: '' },
    { title: 'exhibition', name: 'exhibition', value: '' },
    { title: 'experiential', name: 'experiential', value: '' },
    { title: 'gaming', name: 'gaming', value: 'gaming' },
    { title: 'illustration', name: 'illustration', value: '' },
    { title: 'industrial', name: 'industrial', value: 'industrial' },
    { title: 'interior', name: 'interior', value: '' },
    { title: 'marketing', name: 'marketing', value: '' },
    { title: 'motion', name: 'motion', value: 'motion' },
    { title: 'naming', name: 'naming', value: 'naming' },
    { title: 'packaging', name: 'packaging', value: '' },
    { title: 'photography', name: 'photography', value: '' },
    { title: 'presentation', name: 'presentation', value: '' },
    { title: 'print', name: 'print', value: '' },
    { title: 'product', name: 'product', value: '' },
    { title: 'public relations', name: 'publicRelations', value: '' },
    { title: 'research', name: 'research', value: '' },
    { title: 'education', name: 'education', value: '' },
    { title: 'strategy', name: 'strategy', value: '' },
    { title: 'typography', name: 'typography', value: '' },
    { title: 'UX/UI', name: 'uxui', value: '' },
    { title: 'vfx', name: 'vfx', value: '' },
    { title: 'video', name: 'video', value: '' },
    { title: 'sound', name: 'sound', value: '' },
    { title: 'voice', name: 'voice', value: '' },
    { title: 'virtual reality', name: 'virtualReality', value: '' },
    { title: 'eCommerce', name: 'eCommerce', value: '' },
    {
      title: 'Would you like to be a guest on the show? Or do you want to hear from someone specifically?',
      name: 'submitGuest',
      value: ''
    },
    {
      title: 'Would you buy a hardcopy printed directory?',
      name: 'submitPrint',
      value: 'yes for sure'
    },
    {
      title: 'If you have any questions or suggestions, let us know:',
      name: 'submitNotes',
      value: 'make a map and shit and print it'
    }
  ],
  id: '60afcacb76845800c14b74bd',
  form_id: '60a8684da8b15b0008679fa6',
  site_url: 'https://seattlecreative.directory',
  form_name: 'Submit - Notion'
}
9:37:32 AM 72863ab8 Duration: 11.67 ms	Memory Usage: 67 MB