[build]
  base = "."
  functions = "functions-buildtime"
  publish = "public"
  command = "gatsby build"
[build.environment]
  NODE_VERSION = "14.20.1"
  YARN_VERSION = "1.19.1"
  YARN_FLAGS = "--no-ignore-optional"

[[plugins]]
# Build time link checker
package = "netlify-plugin-checklinks"

  [plugins.inputs]
  todoPatterns = [
    # Server rejections but not fails
    "406",
    "UNABLE_TO_VERIFY_LEAF_SIGNATURE",
    "ERR_TLS_CERT_ALTNAME_INVALID",
    "EAI_AGAIN",
    
    # hard fails
    "500",
    "400",
    "HTTP 403 Forbidden", # Simplecast doesn't like netlify hitting it?
    "ECONNREFUSED",
    "ECONNRESET",
    "DNS missing:",
    "https://design.facebook.com/",
    "https://www.sitecrafting.com/",
    "http://www.oojon.com/",
    "https://www.urbaninfluence.com/",
    "https://www.htc.com/us/",
    
    # Interview pages are generated but unused right now
    'id="interview"'
    ]
  skipPatterns = [
    # assets that don't like the check
    "www.google-analytics.com",
    "https://fonts.googleapis.com/",
    "file:///",

    # usually the result of a number of redirects, then resolving
    "301",
    "302"
  ]

  #turn this off to speed up buildtime
  checkExternal = true
